### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by namlee135** [gaerae/facebook-contest-winner#1]
Hi,

I got error, can you help me?
Thank you.

`Uncaught TypeError: Cannot read property 'id' of undefined
    at Object.pick (<anonymous>:84:29)
    at Object.comment (<anonymous>:25:10)
    at <anonymous>:167:23`

**Comment by gaerae** [comment]
@namlee135 How did you check it? Can you please give us the specific URL or other ways?

**Comment by namlee135** [comment]
Here bro https://www.facebook.com/synam135/posts/2938253909570649
